name: Auto Assign Project to New Issues

on:
  issues:
    types: [opened]

jobs:
  assign-project:
    runs-on: ubuntu-latest
    steps:
      - name: Assign new issue to project
        uses: actions/github-script@v7
        with:
          script: |
            const projectId = '1';
            
            const issue = context.payload.issue;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: `This issue has been added to project #${projectId}`
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}