name: Auto Assign Project to New Issues

on:
  issues:
    types: [opened]

jobs:
  assign-project:
    runs-on: ubuntu-latest
    steps:
      - name: Assign new issue to project
        uses: actions/github-script@v7
        with:
          script: |
            const projectId = '1';
            
            const issue = context.payload.issue;
            
            await github.rest.projects.createCard({
               project_id: projectId,
               content_id: issue.id,
               content_type: 'Issue'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}