name: Auto Assign to Project(s)

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-conventions:
    runs-on: ubuntu-latest

    steps:
      - name: 🔍 Check PR title
        run: |
          echo "🔎 Checking PR title: ${{ github.event.pull_request.title }}"
          TITLE="${{ github.event.pull_request.title }}"
          if [[ ! "$TITLE" =~ ^(feat|fix|chore|docs|refactor|test|style):\ .+ ]]; then
            echo "❌ Invalid PR title convention: '$TITLE'"
            echo "✅ Expected format: 'feat: something here'"
            exit 1
          fi
          echo "✅ PR title is valid."

      - name: 🔍 Check branch name
        run: |
          echo "🔎 Checking branch name: ${{ github.head_ref }}"
          BRANCH="${{ github.head_ref }}"
          if [[ ! "$BRANCH" =~ ^(feat|fix|chore|hotfix)\/[0-9]+(_[0-9]+)?$|^v\.\d+\.\d+\.\d+$ ]]; then
            echo "❌ Invalid branch name convention: '$BRANCH'"
            echo "✅ Expected format: 'feat/1234'"
            exit 1
          fi
          echo "✅ Branch name is valid."